# Generated by Django 3.2.4 on 2021-06-09 09:54

from django.db import migrations, models
import ipaccess.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', ipaccess.core.models.IpNetworkField(max_length=129, null=True, verbose_name='IP Network mast')),
                ('ip_address', ipaccess.core.models.IpAddressField(max_length=129, null=True, verbose_name='Individual IP address')),
                ('reason_for_block', models.TextField(blank=True, help_text='Optional reason for block', null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Rule enabled true/false')),
            ],
            options={
                'verbose_name': 'IPs & masks rules',
                'verbose_name_plural': 'IPs & masks rules',
                'db_table': 'ip_access_rules',
            },
        ),
    ]
